import type { Metadata } from 'next';
import localFont from 'next/font/local';
import React from 'react';

import { cn } from '@/utils/cn';

import Providers from '../components/Providers';
import '../styles/globals.css';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  preload: true,
  fallback: [
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Oxygen',
    'Ubuntu',
    'Cantarell',
    'Helvetica Neue',
    'sans-serif',
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /** TEMP: 임시 배경색 추가 */
    <html lang="ko" className={cn(pretendard.className, 'h-full bg-gray-100 antialiased')}>
      {/** TEMP: max width 임시 값 */}
      <body className="mx-auto my-0 h-full max-w-120 bg-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
