/** `globals.css` @theme `--color-*` 변경 시 이 파일을 동일 규칙으로 다시 생성 (Tailwind purge용) */

/** Tailwind purge: @theme `--color-*`에 대응하는 `bg-*` 유틸을 소스에 고정 노출 */
function ThemeColorTailwindSafelist() {
  return (
    <div
      aria-hidden
      className="pointer-events-none fixed top-0 left-0 -z-10 h-px w-px overflow-hidden opacity-0"
    >
      <span className="bg-base-50" />
      <span className="bg-base-950" />
      <span className="bg-gray-50" />
      <span className="bg-gray-100" />
      <span className="bg-gray-200" />
      <span className="bg-gray-300" />
      <span className="bg-gray-400" />
      <span className="bg-gray-500" />
      <span className="bg-gray-600" />
      <span className="bg-gray-700" />
      <span className="bg-gray-800" />
      <span className="bg-gray-900" />
      <span className="bg-gray-950" />
      <span className="bg-blue-50" />
      <span className="bg-blue-100" />
      <span className="bg-blue-200" />
      <span className="bg-blue-300" />
      <span className="bg-blue-400" />
      <span className="bg-blue-500" />
      <span className="bg-blue-600" />
      <span className="bg-blue-700" />
      <span className="bg-blue-800" />
      <span className="bg-blue-900" />
      <span className="bg-blue-950" />
      <span className="bg-red-50" />
      <span className="bg-red-100" />
      <span className="bg-red-200" />
      <span className="bg-red-300" />
      <span className="bg-red-400" />
      <span className="bg-red-500" />
      <span className="bg-red-600" />
      <span className="bg-red-700" />
      <span className="bg-red-800" />
      <span className="bg-red-900" />
      <span className="bg-red-950" />
      <span className="bg-green-50" />
      <span className="bg-green-100" />
      <span className="bg-green-200" />
      <span className="bg-green-300" />
      <span className="bg-green-400" />
      <span className="bg-green-500" />
      <span className="bg-green-600" />
      <span className="bg-green-700" />
      <span className="bg-green-800" />
      <span className="bg-green-900" />
      <span className="bg-green-950" />
      <span className="bg-yellow-50" />
      <span className="bg-yellow-100" />
      <span className="bg-yellow-200" />
      <span className="bg-yellow-300" />
      <span className="bg-yellow-400" />
      <span className="bg-yellow-500" />
      <span className="bg-yellow-600" />
      <span className="bg-yellow-700" />
      <span className="bg-yellow-800" />
      <span className="bg-yellow-900" />
      <span className="bg-yellow-950" />
      <span className="bg-orange-50" />
      <span className="bg-orange-100" />
      <span className="bg-orange-200" />
      <span className="bg-orange-300" />
      <span className="bg-orange-400" />
      <span className="bg-orange-500" />
      <span className="bg-orange-600" />
      <span className="bg-orange-700" />
      <span className="bg-orange-800" />
      <span className="bg-orange-900" />
      <span className="bg-orange-950" />
      <span className="bg-purple-50" />
      <span className="bg-purple-100" />
      <span className="bg-purple-200" />
      <span className="bg-purple-300" />
      <span className="bg-purple-400" />
      <span className="bg-purple-500" />
      <span className="bg-purple-600" />
      <span className="bg-purple-700" />
      <span className="bg-purple-800" />
      <span className="bg-purple-900" />
      <span className="bg-purple-950" />
      <span className="bg-bg-accent" />
      <span className="bg-bg-warning" />
      <span className="bg-bg-error" />
      <span className="bg-bg-success" />
      <span className="bg-bg-informative" />
      <span className="bg-bg-layer-default" />
      <span className="bg-bg-layer-basement" />
      <span className="bg-bg-layer-overlay" />
      <span className="bg-bg-neutral-primary" />
      <span className="bg-bg-neutral-secondary" />
      <span className="bg-bg-neutral-tertiary" />
      <span className="bg-text-accent" />
      <span className="bg-text-warning" />
      <span className="bg-text-error" />
      <span className="bg-text-success" />
      <span className="bg-text-informative" />
      <span className="bg-text-neutral-primary" />
      <span className="bg-text-neutral-secondary" />
      <span className="bg-text-neutral-tertiary" />
      <span className="bg-text-neutral-inverse" />
      <span className="bg-border-accent" />
      <span className="bg-border-warning" />
      <span className="bg-border-error" />
      <span className="bg-border-success" />
      <span className="bg-border-informative" />
      <span className="bg-border-neutral-primary" />
      <span className="bg-border-neutral-secondary" />
      <span className="bg-border-neutral-tertiary" />
      <span className="bg-border-neutral-muted" />
      <span className="bg-icon-accent" />
      <span className="bg-icon-warning" />
      <span className="bg-icon-error" />
      <span className="bg-icon-success" />
      <span className="bg-icon-informative" />
      <span className="bg-icon-neutral-primary" />
      <span className="bg-icon-neutral-secondary" />
      <span className="bg-icon-neutral-inverse" />
    </div>
  );
}

export default ThemeColorTailwindSafelist;
