export const WEBBRIDGE_MESSAGE_TYPE = {
  OPEN_IMAGE_PICKER: 'OPEN_IMAGE_PICKER',
  IMAGE_PICKER_SUCCESS: 'IMAGE_PICKER_SUCCESS',
  IMAGE_PICKER_CANCEL: 'IMAGE_PICKER_CANCEL',
  IMAGE_PICKER_ERROR: 'IMAGE_PICKER_ERROR',
} as const;
