/**
 * 메시지 네이밍 규칙
 * - WEB_REQ_XXX: 웹 → 앱 요청
 * - APP_RES_XXX: 웹 ← 앱 응답
 * - APP_REQ_XXX: 앱 → 웹 요청
 * - WEB_RES_XXX: 앱 ← 웹 응답
 */
export const WEBBRIDGE_MESSAGE_TYPE = {
  /** 이미지 첨부 관련 */
  OPEN_IMAGE_PICKER: 'OPEN_IMAGE_PICKER',
  IMAGE_PICKER_SUCCESS: 'IMAGE_PICKER_SUCCESS',
  IMAGE_PICKER_CANCEL: 'IMAGE_PICKER_CANCEL',
  IMAGE_PICKER_ERROR: 'IMAGE_PICKER_ERROR',
  /** 소셜 로그인 관련 */
  REQUEST_SOCIAL_LOGIN: 'REQUEST_SOCIAL_LOGIN',
  SOCIAL_LOGIN_SUCCESS: 'SOCIAL_LOGIN_SUCCESS',
  SOCIAL_LOGIN_ERROR: 'SOCIAL_LOGIN_ERROR',
  WEB_REQ_OPEN_IMAGE_PICKER: 'WEB_REQ_OPEN_IMAGE_PICKER',
  APP_RES_IMAGE_PICKER_SUCCESS: 'APP_RES_IMAGE_PICKER_SUCCESS',
  APP_RES_IMAGE_PICKER_CANCEL: 'APP_RES_IMAGE_PICKER_CANCEL',
  APP_RES_IMAGE_PICKER_ERROR: 'APP_RES_IMAGE_PICKER_ERROR',

  /** 앱 → 웹: WEB_REQ_READY에 대한 공유 인텐트 payload 응답 */
  APP_RES_SHARE_INTENT: 'APP_RES_SHARE_INTENT',
  /** 웹 → 앱: 페이지 hydrate 완료, 메시지 수신 준비됨 (ACK 용도) */
  WEB_REQ_READY: 'WEB_REQ_READY',

  /** 푸시 알림 관련 */
  WEB_REQ_PUSH_PERMISSION_STATUS: 'WEB_REQ_PUSH_PERMISSION_STATUS',
  WEB_REQ_PUSH_PERMISSION: 'WEB_REQ_PUSH_PERMISSION',
  WEB_REQ_OPEN_NOTIFICATION_SETTINGS: 'WEB_REQ_OPEN_NOTIFICATION_SETTINGS',
  APP_RES_PUSH_PERMISSION_STATUS: 'APP_RES_PUSH_PERMISSION_STATUS',
  APP_RES_FCM_TOKEN: 'APP_RES_FCM_TOKEN',
} as const;

export const WEB_REQ_READY_PAYLOAD_TYPE = {
  SHARE_INTENT: 'SHARE_INTENT',
} as const;
